### ISSUE TITLE
bi loi speech_recognition

### ISSUE THREAD

**Issue by vietnq2004** [thangnd85/ViPi#1]
[ViPi_0.2] + [KHỞI ĐỘNG CHƯƠNG TRÌNH]
Traceback (most recent call last):
  File "/home/pi/ViPi/src/start.py", line 920, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'
Segmentation fault

Huong dan minh fix loi nay nhe

Cam on
Viet

**Comment by lytranuit** [comment]
Lỗi này do cài thiếu module .gõ lệnh
pip install SpeechRecognition


Vào Th 5, 23 thg 9, 2021 vào lúc 22:36 vietnq2004 <
***@***.***> đã viết:

**Comment by vietnq2004** [comment]
Minh cai pip install SpeechRecognition roi
No van bao loi nhu tren
